### ISSUE TITLE
printtyにデータアップロードできない

### ISSUE THREAD

**Issue by hirokiokano** [DecodeLLC/couple-t-web-admin#43]
![default](https://cloud.githubusercontent.com/assets/17420901/26812105/bea88c00-4ab0-11e7-851e-50e1a70c41d3.JPG)

**Comment by alexeypolitov** [comment]
@hirokiokano @tomoyuki1110 @take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
こちらはアップできています。
