### ISSUE TITLE
プレゼントの場合、注文完了メールに相手の個人情報が入ってしまう

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-web-admin#46]
プレゼントの場合、プレゼントされる側の情報は送る側に見せないようにお願いします。
プレゼントの場合のメールのお届け先は、相手のユーザー名だけにしてください。

これは、緊急性高いです。
急ぎ対応をお願いします。

以下のメール文がプレゼントを<strong>送る側</strong>にきています。
![_2017-07-25_12_12_07](https://user-images.githubusercontent.com/23730555/28554367-1300f8b0-7134-11e7-9123-3d8df6c7c931.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。開発環境でご確認下さい。

**Comment by take-iwa** [comment]
@alexeypolitov 本番で確認していたのですが、やはり上と同じように送る相手の名前、住所が入っています。確認お願いします。

また、gmail.comには届きましたが、maruiorimono.jpにはメール自体が届かず。。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ロジクの問題であれば相談させてください。
maruiorimono.jpには迷惑のフィルターが動いてると思います

**Comment by take-iwa** [comment]
@alexeypolitov TestFlightのv1.0.8(1)で確認しました。
直っていません。
最初のユーザー名も配送先もプレゼントされる人のものが入ってしまっています。

**Comment by alexeypolitov** [comment]
@take-iwa 二つメールが送られてると思います。こちらにアップしていただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov ごめんなさい。２つのメールとはどういった内容のメールでしたか？

**Comment by alexeypolitov** [comment]
@take-iwa 注文した人にメールのと送り先のメールです。プレゼントもらってる側のことです
