### ISSUE TITLE
up-tと同じように納品書を出したい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-web-admin#47]
up-tと同じように納品書のデータを作成し、
工場側でプリントアウトができるようにお願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。開発環境でご確認下さい。

**Comment by take-iwa** [comment]
工場側での納品書出力確認できました。

[G001-2017-08-20-0558e265f02c9152b3ea457a785989b1ce65344c.pdf](https://github.com/DecodeLLC/couple-t-web-admin/files/1233710/G001-2017-08-20-0558e265f02c9152b3ea457a785989b1ce65344c.pdf)
