### ISSUE TITLE
相手にプレゼントの場合、注文データが管理画面に入らない。

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-web-admin#48]
相手に購入した時、管理画面に注文が入らないです。

あと思ったのですが、相手にプレゼントする場合、色やサイズってどこで指定するのでしょうか？
どういったフローを想定してますでしょうか？

**Comment by alexeypolitov** [comment]
@take-iwa カラーやサイズなど購入者側でしか選べないです。以前からそうです

**Comment by take-iwa** [comment]
@alexeypolitov プレゼントする側ということですよね。
だとすると、相手にプレセント購入した時に出る注文画面でカラー、サイズを選べるようにお願いします。

![img_0027](https://user-images.githubusercontent.com/23730555/29456435-8f566e7a-8450-11e7-9282-f0b1b1b9fc02.PNG)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ロジクの問題であれば相談させてください。

**Comment by take-iwa** [comment]
@alexeypolitov TestFlightのv1.0.8(1)で確認しましたが、購入時にサイズ・カラー選べないです。
また、プレゼント購入で決済方法から銀行振込がなくなっています。意図的でしょうか？

クレカ払いで注文入れてみましたが、注文履歴にも管理画面にも注文が入りませんでした。

**Comment by take-iwa** [comment]
相手の方でサイズと住所を設定したら、管理画面に出ました。OKです。
